version: '3'
services:
  spark-master:
    container_name: spark-master
    build:
      context: ./spark
      dockerfile: spark-1.6.docker
    image: spark-master
    ports:
      - 8080:8080
      - 7077:7077
    env_file:
      - ./hadoop-hive.env
  spark-worker:
#  hive-server:
#  hive-metastore:
#  hive-metastore-postgresql:
#  hdfs-namenode:
#  hdfs-datanode:
#  hue: